name: CPU Linux Build and Test
on: [push]
jobs:
  build:
    runs-on: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: |
          cargo build || exit 1
      - name: Test
        run: |
          cargo --test || exit 1