name: CPU Linux Build and Test
on: [push]
jobs:
  build:
    runs:
      using: docker
      image: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build || exit 1
      - name: Test
        run: |
          cargo --test || exit 1