name: Continuous Integration

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: Berling/rust-build@v1

      - name: Report
        id: report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
          verbose: true

      - name: Check Total Coverage
        id: total-coverage
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | sed -e "s/^$GITHUB_REPOSITORY_OWNER\///")
          TOTAL_COVERAGE=$(curl --location --request GET 'https://codecov.io/api/v2/github/$GITHUB_REPOSITORY_OWNER/repos/pbrt/totals?branch=$GITHUB_REF_NAME' --header 'Authorization: bearer $CODECOV_API_TOKEN' | jq .totals.coverage)
          if [ "$(echo "$TOTAL_COVERAGE < 80.0" | bc)" -eq 1  ]; then
            exit 1
          fi
