name: Continuous Integration

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: Berling/rust-build@v1

      - name: Report
        id: report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
          verbose: true

      - name: Check Total Coverage
        id: total-coverage
        run: |
          set -ex
          export REPO_NAME=$(echo "${{ github.repository }}" | sed -e "s/^${{ github.repository_owner }}\///")
          export TOTAL_COVERAGE=$(curl --location --request GET "https://codecov.io/api/v2/github/${{ github.repository_owner }}/repos/$REPO_NAME/totals?branch=${{ github.ref_name }}" --header "Authorization: bearer ${{ secrets.CODECOV_API_TOKEN }}" | jq .totals.coverage)
          if [ "$(echo "$TOTAL_COVERAGE < 80.0" | bc)" -eq 1  ]; then
            echo "::error title=Code Coverage Target Missed::Total code coverage is below threshold of '80.0%'"
            exit 1
          fi
